# {{ display_name }} API

This API endpoint is part of the Homelab Infrastructure Management Platform (HIMP).

## Purpose

Describe the purpose of the {{ display_name }} API.

## Endpoints

| Method | Path | Description |
|---------|------|-------------|
| GET | /{{ name }} | Retrieve {{ display_name }} information |

## Notes

- Generated by HIMP Builder.
