#!/usr/sbin/nft -f

flush ruleset

table inet filter {
        chain input {
                type filter hook input priority filter;
                policy accept;

                iif lo accept

                ip saddr 192.168.37.0/24 tcp dport 80 accept
                ip saddr 192.168.10.0/24 tcp dport 80 accept
                ip saddr 10.10.37.0/24 tcp dport 80 accept
                tcp dport 80 drop

                ip saddr 192.168.37.0/24 tcp dport 443 accept
                ip saddr 192.168.10.0/24 tcp dport 443 accept
                ip saddr 10.10.37.0/24 tcp dport 443 accept
                tcp dport 443 drop

                tcp dport 9347 drop
        }

        chain forward {
                type filter hook forward priority filter;
                policy accept;
        }

        chain output {
                type filter hook output priority filter;
                policy accept;
        }
}
