import re

from himp.database.postgresql_schema import (
    schema_statements,
)


EXPECTED_TABLES = {
    "asset_relationships",
    "automation_dependencies",
    "automation_executions",
    "automation_locks",
    "automation_schedules",
    "discovery",
    "executions",
    "health_history",
    "host_health_history",
    "inventory_baselines",
    "inventory_changes",
    "inventory_hosts",
    "maintenance_windows",
    "notification_deliveries",
    "notifications",
    "remediation_audit",
    "remediation_approvals",
    "remediation_schedules",
    "remediation_operations",
    "sessions",
    "storage_alert_events",
    "storage_capacity_history",
    "users",
    "workflow_dependencies",
    "workflow_executions",
    "workflow_tasks",
    "workflows",
    "vulnerability_reports",
    "vulnerability_findings",
}


def table_name(statement):
    match = re.search(
        r"CREATE TABLE IF NOT EXISTS\s+([a-z_]+)",
        statement,
        re.IGNORECASE,
    )

    assert match is not None

    return match.group(1)


def test_schema_defines_every_himp_table_once():
    statements = schema_statements()

    names = [
        table_name(statement)
        for statement in statements
    ]

    assert len(statements) == 29

    assert "vulnerability_reports" in names
    assert "vulnerability_findings" in names
    assert len(names) == len(set(names))
    assert set(names) == EXPECTED_TABLES


def test_schema_contains_no_sqlite_specific_ddl():
    combined = "\n".join(
        schema_statements()
    ).upper()

    assert "AUTOINCREMENT" not in combined
    assert "PRAGMA" not in combined
    assert "BEGIN IMMEDIATE" not in combined


def test_generated_primary_keys_use_postgresql_identity():
    statements = {
        table_name(statement): statement.upper()
        for statement in schema_statements()
    }

    identity_tables = EXPECTED_TABLES - {
        "automation_locks",
        "remediation_operations",
        "users",
    }

    for name in identity_tables:
        assert (
            "GENERATED BY DEFAULT AS IDENTITY"
            in statements[name]
        )


def test_singleton_and_natural_primary_keys_are_preserved():
    statements = {
        table_name(statement): statement.upper()
        for statement in schema_statements()
    }

    assert (
        "TASK_ID TEXT PRIMARY KEY"
        in statements["automation_locks"]
    )

    assert (
        "ID INTEGER PRIMARY KEY CHECK (ID = 1)"
        in statements["remediation_operations"]
    )

    assert (
        "USERNAME TEXT PRIMARY KEY"
        in statements["users"]
    )


def test_workflow_foreign_keys_preserve_cascade_semantics():
    statements = {
        table_name(statement): statement.upper()
        for statement in schema_statements()
    }

    for name in (
        "workflow_tasks",
        "workflow_dependencies",
    ):
        assert (
            "REFERENCES WORKFLOWS(ID)"
            in statements[name]
        )
        assert (
            "ON DELETE CASCADE"
            in statements[name]
        )


def test_historical_additive_columns_are_in_base_schema():
    statements = {
        table_name(statement): statement.upper()
        for statement in schema_statements()
    }

    for column in (
        "STDOUT TEXT",
        "STDERR TEXT",
        "WARNINGS TEXT",
        "ARTIFACTS TEXT",
    ):
        assert column in statements["executions"]

    assert (
        "WORKFLOW_EXECUTION_ID TEXT"
        in statements["automation_executions"]
    )

    assert (
        "RETRY_OF_EXECUTION_ID BIGINT"
        in statements["automation_executions"]
    )

    assert (
        "RETRY_SOURCE_WORKFLOW_EXECUTION_ID TEXT"
        in statements["automation_executions"]
    )

    assert (
        "REPLAY_OF_WORKFLOW_EXECUTION_ID TEXT"
        in statements["workflow_executions"]
    )

    assert (
        "DAY_OF_MONTH INTEGER"
        in statements["automation_schedules"]
    )

    assert (
        "CURRENT_TASK_ID TEXT"
        in statements["workflow_executions"]
    )


def test_logical_flags_remain_integer_compatible():
    combined = "\n".join(
        schema_statements()
    ).upper()

    assert " BOOLEAN" not in combined

    expected_checks = (
        "SUCCESS IN (0, 1)",
        "BECOME IN (0, 1)",
        "ACTIVE IN (0, 1)",
        "ENABLED IN (0, 1)",
        "CONFIRMATION_REQUIRED IN (0, 1)",
        "CONFIRMED IN (0, 1)",
        "PASSWORD_CHANGE_REQUIRED IN (0, 1)",
    )

    for check in expected_checks:
        assert check in combined


def test_schema_creation_order_precedes_workflow_dependents():
    names = [
        table_name(statement)
        for statement in schema_statements()
    ]

    workflow_position = names.index(
        "workflows"
    )

    assert workflow_position < names.index(
        "workflow_tasks"
    )

    assert workflow_position < names.index(
        "workflow_dependencies"
    )


def test_remediation_audit_schema_contains_verification_outcome():
    statements = {
        table_name(statement): statement.upper()
        for statement in schema_statements()
    }

    audit = statements[
        "remediation_audit"
    ]

    assert (
        "VERIFICATION_STATUS TEXT"
        in audit
    )

    assert (
        "VERIFICATION_SUCCESS INTEGER"
        in audit
    )

    assert (
        "VERIFICATION_EVIDENCE TEXT"
        in audit
    )
