---
###############################################################################
# HIMP CMDB Builder
###############################################################################

- name: Load health configuration
  ansible.builtin.include_vars:
    file: ../vars/health.yml

- import_tasks: metadata.yml
- import_tasks: network.yml
- import_tasks: hardware.yml
- import_tasks: storage.yml
- import_tasks: services.yml
- import_tasks: security.yml
- import_tasks: monitoring.yml
- import_tasks: health.yml

- import_tasks: assemble.yml
