---
###############################################################################
# CMDB Metadata
###############################################################################

- name: Build metadata section
  ansible.builtin.set_fact:
    cmdb_metadata:
      id: "{{ inventory_hostname }}"
      hostname: "{{ inventory_hostname }}"
      fqdn: "{{ ansible_fqdn | default('') }}"
      inventory_group: "{{ group_names }}"
      service: "{{ service | default('Unknown') }}"
      role: "{{ role | default('Unknown') }}"
      category: "{{ category | default('General') }}"
      vendor: "{{ vendor | default('Unknown') }}"
      platform: "{{ platform | default(ansible_system) }}"
      environment: "{{ environment | default('Homelab', true) }}"
      site: "{{ site | default('Primary') }}"
      priority: "{{ priority | default('Normal') }}"
      icon: "{{ icon | default('🖥️') }}"
