"""
Host Automation Policy Repository.

Stores operator-controlled maintenance exclusions independently
from synchronized inventory state.
"""

from datetime import datetime, timezone

from himp.database.factory import create_database


class HostAutomationPolicyRepository:
    """Persistent host automation policy and audit history."""

    def __init__(self, database=None):
        self.database = (
            database
            if database is not None
            else create_database()
        )
        self.initialize()

    def initialize(self):
        """Create policy and audit tables on either supported backend."""
        self.database.execute(
            """
            CREATE TABLE IF NOT EXISTS host_automation_policies
            (
                hostname TEXT PRIMARY KEY,
                enabled INTEGER NOT NULL DEFAULT 1,
                reason TEXT NOT NULL DEFAULT '',
                changed_by TEXT NOT NULL,
                changed_at TIMESTAMP NOT NULL,
                CHECK (enabled IN (0, 1))
            )
            """
        )

        # SQLite and PostgreSQL use different identity-column syntax.
        if hasattr(self.database, "_normalize_sql"):
            audit_id = (
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            )
        else:
            audit_id = (
                "INTEGER PRIMARY KEY AUTOINCREMENT"
            )

        self.database.execute(
            f"""
            CREATE TABLE IF NOT EXISTS host_automation_policy_audit
            (
                id {audit_id},
                hostname TEXT NOT NULL,
                old_enabled INTEGER NOT NULL,
                new_enabled INTEGER NOT NULL,
                reason TEXT NOT NULL,
                changed_by TEXT NOT NULL,
                changed_at TIMESTAMP NOT NULL,
                CHECK (old_enabled IN (0, 1)),
                CHECK (new_enabled IN (0, 1))
            )
            """
        )

    @staticmethod
    def _now():
        return datetime.now(
            timezone.utc
        ).replace(tzinfo=None)

    def get(self, hostname):
        rows = self.database.query(
            """
            SELECT
                hostname,
                enabled,
                reason,
                changed_by,
                changed_at
            FROM host_automation_policies
            WHERE hostname=?
            LIMIT 1
            """,
            (hostname,),
        )

        if not rows:
            return {
                "hostname": hostname,
                "enabled": True,
                "reason": "",
                "changed_by": None,
                "changed_at": None,
            }

        row = dict(rows[0])
        row["enabled"] = bool(row["enabled"])
        return row

    def disabled_hosts(self):
        rows = self.database.query(
            """
            SELECT hostname
            FROM host_automation_policies
            WHERE enabled=0
            ORDER BY hostname
            """
        )

        return {
            row["hostname"]
            for row in rows
        }

    def set_policy(
        self,
        hostname,
        enabled,
        reason,
        changed_by,
    ):
        if not isinstance(hostname, str):
            raise ValueError("hostname must be a string")

        if not isinstance(reason, str):
            raise ValueError("reason must be a string")

        if not isinstance(changed_by, str):
            raise ValueError("changed_by must be a string")

        hostname = hostname.strip()
        reason = reason.strip()
        changed_by = changed_by.strip()

        if not hostname:
            raise ValueError("hostname is required")

        if not changed_by:
            raise ValueError("changed_by is required")

        if not isinstance(enabled, bool):
            raise ValueError("enabled must be boolean")

        if not enabled and not reason:
            raise ValueError(
                "A reason is required when disabling automation"
            )

        now = self._now()

        with self.database.transaction() as connection:
            cursor = connection.cursor()

            try:
                # PostgreSQL: serialize changes for the same host.
                # SQLite uses its existing write transaction behavior.
                if hasattr(self.database, "_normalize_sql"):
                    cursor.execute(
                        """
                        SELECT pg_advisory_xact_lock(
                            hashtextextended(%s, 0)
                        )
                        """,
                        (hostname,),
                    )

                cursor.execute(
                    self.database._normalize_sql(
                        """
                        SELECT enabled
                        FROM host_automation_policies
                        WHERE hostname=?
                        """
                    ) if hasattr(
                        self.database,
                        "_normalize_sql",
                    ) else
                    """
                    SELECT enabled
                    FROM host_automation_policies
                    WHERE hostname=?
                    """,
                    (hostname,),
                )

                previous = cursor.fetchone()

                old_enabled = (
                    bool(previous["enabled"])
                    if previous is not None
                    else True
                )

                statements = (
                    (
                        """
                        INSERT INTO host_automation_policies
                        (
                            hostname,
                            enabled,
                            reason,
                            changed_by,
                            changed_at
                        )
                        VALUES (?, ?, ?, ?, ?)
                        ON CONFLICT(hostname)
                        DO UPDATE SET
                            enabled=excluded.enabled,
                            reason=excluded.reason,
                            changed_by=excluded.changed_by,
                            changed_at=excluded.changed_at
                        """,
                        (
                            hostname,
                            int(enabled),
                            reason,
                            changed_by,
                            now,
                        ),
                    ),
                    (
                        """
                        INSERT INTO host_automation_policy_audit
                        (
                            hostname,
                            old_enabled,
                            new_enabled,
                            reason,
                            changed_by,
                            changed_at
                        )
                        VALUES (?, ?, ?, ?, ?, ?)
                        """,
                        (
                            hostname,
                            int(old_enabled),
                            int(enabled),
                            reason,
                            changed_by,
                            now,
                        ),
                    ),
                )

                for sql, parameters in statements:
                    if hasattr(
                        self.database,
                        "_normalize_sql",
                    ):
                        sql = self.database._normalize_sql(sql)

                    cursor.execute(sql, parameters)

            finally:
                cursor.close()

        return self.get(hostname)

    def history(self, hostname, limit=100):
        """Return recent audit records for a host."""
        if not isinstance(hostname, str) or not hostname.strip():
            raise ValueError("hostname is required")

        if (
            isinstance(limit, bool)
            or not isinstance(limit, int)
            or limit < 1
        ):
            raise ValueError(
                "limit must be a positive integer"
            )

        limit = min(limit, 500)

        rows = self.database.query(
            """
            SELECT id, hostname, old_enabled, new_enabled,
                   reason, changed_by, changed_at
            FROM host_automation_policy_audit
            WHERE hostname = ?
            ORDER BY id DESC
            LIMIT ?
            """,
            (hostname.strip(), limit),
        )

        result = []
        for row in rows:
            entry = dict(row)
            entry["old_enabled"] = bool(entry["old_enabled"])
            entry["new_enabled"] = bool(entry["new_enabled"])
            result.append(entry)

        return result
