"""
PostgreSQL database backend.

Provides HIMP's PostgreSQL database contract through a bounded,
process-local connection pool. Repository database objects do not own
permanent PostgreSQL sessions. Ordinary operations borrow a connection
for the duration of the operation, while explicit transactions pin one
connection for the complete transaction boundary.
"""

from contextlib import contextmanager
from threading import Lock

import psycopg
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from himp.database.config import DatabaseConfig
from himp.database.postgresql_schema import (
    schema_statements,
)


class PostgreSQLDatabase:
    _pools = {}
    _pools_lock = Lock()

    POOL_MIN_SIZE = 1
    POOL_MAX_SIZE = 8
    POOL_TIMEOUT = 10

    def __init__(
        self,
        config=None,
    ):
        self.config = (
            config
            if config is not None
            else DatabaseConfig.from_environment()
        )

        if not self.config.is_postgresql:
            raise ValueError(
                "PostgreSQLDatabase requires "
                "backend=postgresql."
            )

        self.pool = self._get_pool(
            self.config
        )

    @classmethod
    def _pool_key(
        cls,
        config,
    ):
        return (
            config.postgres_host,
            config.postgres_port,
            config.postgres_database,
            config.postgres_user,
            config.postgres_password,
        )

    @classmethod
    def _get_pool(
        cls,
        config,
    ):
        key = cls._pool_key(
            config
        )

        with cls._pools_lock:
            pool = cls._pools.get(
                key
            )

            if pool is None:
                pool = ConnectionPool(
                    conninfo="",
                    kwargs={
                        "host": config.postgres_host,
                        "port": config.postgres_port,
                        "dbname": config.postgres_database,
                        "user": config.postgres_user,
                        "password": config.postgres_password,
                        "row_factory": dict_row,
                        "autocommit": True,
                    },
                    min_size=cls.POOL_MIN_SIZE,
                    max_size=cls.POOL_MAX_SIZE,
                    timeout=cls.POOL_TIMEOUT,
                    open=True,
                )

                cls._pools[key] = pool

        return pool

    @staticmethod
    def _normalize_sql(sql):
        """
        Normalize repository SQL for PostgreSQL.

        HIMP repositories historically use SQLite-compatible SQL.
        Preserve that repository contract while translating the small
        backend-specific surface at the PostgreSQL boundary.
        """
        normalized = sql.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            (
                "BIGINT GENERATED BY DEFAULT "
                "AS IDENTITY PRIMARY KEY"
            ),
        )

        return normalized.replace(
            "?",
            "%s",
        )

    def execute(
        self,
        sql,
        parameters=(),
    ):
        """
        Execute a statement using a pooled connection.

        The cursor never escapes the checkout boundary.
        """
        with self.pool.connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    self._normalize_sql(sql),
                    parameters,
                )

        return None

    def execute_affected(
        self,
        sql,
        parameters=(),
    ):
        """
        Execute a statement and return its affected-row count.

        Row-count consumers receive a detached integer rather than
        a cursor tied to a connection that has returned to the pool.
        """
        with self.pool.connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    self._normalize_sql(sql),
                    parameters,
                )

                return cursor.rowcount

    def query(
        self,
        sql,
        parameters=(),
    ):
        with self.pool.connection() as connection:
            cursor = connection.cursor()

            cursor.execute(
                self._normalize_sql(sql),
                parameters,
            )

            return cursor.fetchall()

    @contextmanager
    def transaction(self):
        """
        Pin one pooled connection for an explicit repository transaction.
        """
        with self.pool.connection() as connection:
            with connection.transaction():
                yield connection

    @contextmanager
    def connection(self):
        """
        Pin one pooled connection without implicitly opening a transaction.

        This compatibility boundary supports operations such as database
        migration that need direct cursor access while still ensuring the
        PostgreSQL session is returned to the shared pool.
        """
        with self.pool.connection() as connection:
            yield connection

    def initialize_schema(self):
        """
        Initialize the complete HIMP PostgreSQL schema atomically.

        Every schema statement is executed inside one PostgreSQL
        transaction. If any statement fails, PostgreSQL rolls back
        the entire schema initialization.
        """
        with self.transaction() as connection:
            with connection.cursor() as cursor:
                for statement in schema_statements():
                    cursor.execute(statement)

    def close(self):
        """
        Release this database facade.

        Connections are owned by the process-wide pool rather than by
        individual repository database objects, so there is no dedicated
        connection to close here.
        """
        return None

    @classmethod
    def close_pools(cls):
        """
        Close every process-local PostgreSQL pool.

        Intended for orderly process shutdown and tests.
        """
        with cls._pools_lock:
            pools = tuple(
                cls._pools.values()
            )
            cls._pools.clear()

        for pool in pools:
            pool.close()

    def table_columns(
        self,
        table_name,
    ):
        """
        Return the column names for a PostgreSQL table in the
        current schema.
        """
        rows = self.query(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = ?
            ORDER BY ordinal_position
            """,
            (
                table_name,
            ),
        )

        return {
            row["column_name"]
            for row in rows
        }

    def execute_insert(
        self,
        sql,
        parameters=(),
    ):
        """
        Execute an INSERT and return its generated integer ID.
        """
        normalized_sql = sql.rstrip().rstrip(";")

        if "returning" not in normalized_sql.lower():
            normalized_sql += " RETURNING id"

        with self.pool.connection() as connection:
            cursor = connection.cursor()

            cursor.execute(
                self._normalize_sql(
                    normalized_sql
                ),
                parameters,
            )

            row = cursor.fetchone()

        if row is None:
            raise RuntimeError(
                "PostgreSQL INSERT did not return "
                "a generated identifier."
            )

        return row["id"]

    @staticmethod
    def is_integrity_error(exception):
        """
        Return whether an exception represents a PostgreSQL
        integrity/constraint violation.
        """
        return isinstance(
            exception,
            psycopg.IntegrityError,
        )

    def begin_lock_transaction(
        self,
        connection,
    ):
        """
        PostgreSQL transaction serialization is provided by its
        transaction/constraint semantics. No SQLite-style
        BEGIN IMMEDIATE statement is required.
        """
        return None

    def execute_transaction(
        self,
        connection,
        sql,
        parameters=(),
    ):
        """
        Execute repository SQL on an existing PostgreSQL transaction
        connection while preserving normal backend SQL translation.
        """
        return connection.execute(
            self._normalize_sql(sql),
            parameters,
        )
