"""
PostgreSQL schema definition for HIMP.

This module contains only deterministic PostgreSQL DDL.
It does not open database connections or apply the schema.

SQLite-compatible logical boolean values remain INTEGER
during the initial PostgreSQL migration so existing repository
write semantics remain unchanged.
"""

POSTGRESQL_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS executions
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plugin TEXT NOT NULL,
        success INTEGER NOT NULL CHECK (success IN (0, 1)),
        return_code INTEGER NOT NULL,
        elapsed DOUBLE PRECISION NOT NULL,
        executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        stdout TEXT,
        stderr TEXT,
        warnings TEXT,
        artifacts TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS health_history
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plugin TEXT NOT NULL,
        status TEXT NOT NULL,
        score INTEGER NOT NULL,
        possible INTEGER NOT NULL,
        issues TEXT,
        metadata TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS inventory_hosts
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hostname TEXT NOT NULL UNIQUE,
        group_name TEXT,
        ip TEXT,
        ansible_user TEXT,
        become INTEGER NOT NULL CHECK (become IN (0, 1)),
        active INTEGER NOT NULL DEFAULT 1
            CHECK (active IN (0, 1)),
        first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS inventory_changes
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hostname TEXT NOT NULL,
        change_type TEXT NOT NULL,
        field TEXT,
        old_value TEXT,
        new_value TEXT,
        changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS inventory_baselines
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        hosts TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS workflows
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        description TEXT NOT NULL DEFAULT '',
        enabled INTEGER NOT NULL DEFAULT 1
            CHECK (enabled IN (0, 1)),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS workflow_tasks
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id BIGINT NOT NULL,
        task_id TEXT NOT NULL,
        position INTEGER NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(workflow_id, task_id),
        FOREIGN KEY(workflow_id)
            REFERENCES workflows(id)
            ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS workflow_dependencies
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id BIGINT NOT NULL,
        task_id TEXT NOT NULL,
        depends_on_task_id TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(
            workflow_id,
            task_id,
            depends_on_task_id
        ),
        FOREIGN KEY(workflow_id)
            REFERENCES workflows(id)
            ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS workflow_executions
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id BIGINT NOT NULL,
        workflow_execution_id TEXT NOT NULL UNIQUE,
        started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        completed_at TIMESTAMP,
        success INTEGER CHECK (success IN (0, 1)),
        current_task_id TEXT,
        replay_of_workflow_execution_id TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS automation_dependencies
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id TEXT NOT NULL,
        depends_on_task_id TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(
            task_id,
            depends_on_task_id
        )
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS asset_relationships
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_type TEXT NOT NULL,
        source_id TEXT NOT NULL,
        relationship_type TEXT NOT NULL,
        target_type TEXT NOT NULL,
        target_id TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(
            source_type,
            source_id,
            relationship_type,
            target_type,
            target_id
        )
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS automation_executions
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id TEXT NOT NULL,
        workflow_execution_id TEXT,
        retry_of_execution_id BIGINT,
        retry_source_workflow_execution_id TEXT,
        success INTEGER NOT NULL CHECK (success IN (0, 1)),
        elapsed DOUBLE PRECISION NOT NULL,
        result TEXT,
        executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS automation_locks
    (
        task_id TEXT PRIMARY KEY,
        locked_at TIMESTAMP NOT NULL,
        expires_at TIMESTAMP NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS automation_schedules
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        task_id TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        enabled INTEGER NOT NULL DEFAULT 1
            CHECK (enabled IN (0, 1)),
        frequency TEXT NOT NULL DEFAULT 'manual',
        schedule_time TEXT,
        day_of_week INTEGER,
        day_of_month INTEGER,
        last_run TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS remediation_audit
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_type TEXT NOT NULL,
        source_id TEXT NOT NULL,
        task_id TEXT NOT NULL,
        decision TEXT NOT NULL,
        reason TEXT NOT NULL,
        evidence TEXT,
        risk_level TEXT,
        confirmation_required INTEGER NOT NULL
            CHECK (confirmation_required IN (0, 1)),
        confirmed INTEGER NOT NULL
            CHECK (confirmed IN (0, 1)),
        execution_id BIGINT,
        execution_success INTEGER
            CHECK (
                execution_success IS NULL
                OR execution_success IN (0, 1)
            ),
        verification_status TEXT,
        verification_success INTEGER
            CHECK (
                verification_success IS NULL
                OR verification_success IN (0, 1)
            ),
        verification_evidence TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS remediation_approvals
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        recommendation_id TEXT NOT NULL,
        task_id TEXT NOT NULL DEFAULT 'scheduled_updates',
        source_type TEXT NOT NULL,
        source_id TEXT NOT NULL,
        target_type TEXT NOT NULL,
        target_id TEXT NOT NULL,
        condition TEXT NOT NULL,
        severity TEXT NOT NULL,
        recommended_action TEXT NOT NULL,
        rationale TEXT NOT NULL,
        evidence TEXT NOT NULL,
        affected_assets TEXT NOT NULL,
        dependency_depth INTEGER,
        dependency_path TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'PENDING'
            CHECK (
                status IN (
                    'PENDING',
                    'APPROVED',
                    'DENIED'
                )
            ),
        requested_by TEXT NOT NULL,
        decided_by TEXT,
        decision_note TEXT,
        created_at TIMESTAMP NOT NULL,
        decided_at TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS remediation_schedules
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        approval_id BIGINT NOT NULL UNIQUE,
        scheduled_for TIMESTAMP NOT NULL,
        status TEXT NOT NULL DEFAULT 'SCHEDULED'
            CHECK (
                status IN (
                    'SCHEDULED',
                    'RUNNING',
                    'COMPLETED',
                    'FAILED',
                    'CANCELLED'
                )
            ),
        scheduled_by TEXT NOT NULL,
        started_at TIMESTAMP,
        completed_at TIMESTAMP,
        audit_id BIGINT,
        error TEXT,
        cancelled_by TEXT,
        cancellation_note TEXT,
        cancelled_at TIMESTAMP,
        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS remediation_operations
    (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        enabled INTEGER NOT NULL DEFAULT 0
            CHECK (enabled IN (0, 1)),
        source_type TEXT NOT NULL,
        source_id TEXT NOT NULL,
        baseline TEXT,
        change_limit INTEGER NOT NULL DEFAULT 10,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sessions
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token_hash TEXT NOT NULL UNIQUE,
        username TEXT NOT NULL,
        created_at TIMESTAMP NOT NULL,
        expires_at TIMESTAMP NOT NULL,
        revoked_at TIMESTAMP,
        last_seen_at TIMESTAMP NOT NULL,
        CHECK (length(token_hash) = 64),
        CHECK (length(username) > 0),
        CHECK (expires_at > created_at)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS users
    (
        username TEXT PRIMARY KEY,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL,
        active INTEGER NOT NULL DEFAULT 1
            CHECK (active IN (0, 1)),
        display_name TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP NOT NULL,
        last_login_at TIMESTAMP,
        failed_login_attempts INTEGER NOT NULL DEFAULT 0,
        password_change_required INTEGER NOT NULL DEFAULT 0
            CHECK (password_change_required IN (0, 1)),
        CHECK (
            role IN (
                'admin',
                'operator',
                'viewer'
            )
        ),
        CHECK (failed_login_attempts >= 0)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS discovery
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plugin TEXT NOT NULL,
        hostname TEXT NOT NULL,
        category TEXT NOT NULL,
        name TEXT NOT NULL,
        value TEXT,
        discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS storage_capacity_history
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hostname TEXT NOT NULL,
        filesystem TEXT NOT NULL,
        mount_point TEXT NOT NULL,
        total_bytes BIGINT NOT NULL,
        used_bytes BIGINT NOT NULL,
        available_bytes BIGINT NOT NULL,
        used_percent DOUBLE PRECISION NOT NULL,
        status TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS storage_alert_events
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hostname TEXT NOT NULL,
        filesystem TEXT NOT NULL,
        mount_point TEXT NOT NULL,
        previous_status TEXT,
        current_status TEXT NOT NULL,
        event_type TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS notifications
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        event_type TEXT NOT NULL,
        source_type TEXT NOT NULL,
        source_id TEXT NOT NULL,
        severity TEXT NOT NULL,

        title TEXT NOT NULL,
        message TEXT NOT NULL,

        deduplication_key TEXT NOT NULL,
        correlation_key TEXT NOT NULL,

        lifecycle_status TEXT NOT NULL
            CHECK (
                lifecycle_status IN (
                    'PENDING',
                    'SUPPRESSED',
                    'ACKNOWLEDGED',
                    'RECOVERED'
                )
            ),

        routing_decision TEXT NOT NULL
            CHECK (
                routing_decision IN (
                    'ROUTE',
                    'SUPPRESS'
                )
            ),

        logical_destinations TEXT NOT NULL,
        suppression_reason TEXT,

        metadata TEXT NOT NULL,

        occurred_at TIMESTAMP NOT NULL,

        acknowledged_by TEXT,
        acknowledged_at TIMESTAMP,

        recovered_at TIMESTAMP,

        created_at TIMESTAMP NOT NULL,
        updated_at TIMESTAMP NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS notification_deliveries
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        notification_id BIGINT NOT NULL,
        destination_type TEXT NOT NULL,
        destination_name TEXT NOT NULL,
        status TEXT NOT NULL
            CHECK (
                status IN (
                    'SUCCESS',
                    'FAILED',
                    'SKIPPED'
                )
            ),
        status_code INTEGER,
        error TEXT,
        attempted_at TIMESTAMP NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS host_health_history
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hostname TEXT NOT NULL,
        check_name TEXT NOT NULL,
        status TEXT NOT NULL,
        message TEXT,
        duration_ms DOUBLE PRECISION NOT NULL,
        details TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
)


def schema_statements():
    """
    Return the PostgreSQL schema statements in dependency-safe
    creation order.
    """
    return POSTGRESQL_SCHEMA_STATEMENTS
