"""
PostgreSQL database backend.

Phase 11 foundation for PostgreSQL connectivity. This backend intentionally
does not initialize HIMP schema yet; schema migration is handled by later
Phase 11 slices.
"""

from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row

from himp.database.config import DatabaseConfig
from himp.database.postgresql_schema import (
    schema_statements,
)


class PostgreSQLDatabase:

    def __init__(
        self,
        config=None,
    ):
        self.config = (
            config
            if config is not None
            else DatabaseConfig.from_environment()
        )

        if not self.config.is_postgresql:
            raise ValueError(
                "PostgreSQLDatabase requires "
                "backend=postgresql."
            )

        self.connection = psycopg.connect(
            host=self.config.postgres_host,
            port=self.config.postgres_port,
            dbname=self.config.postgres_database,
            user=self.config.postgres_user,
            password=self.config.postgres_password,
            row_factory=dict_row,
            autocommit=True,
        )

    @staticmethod
    def _normalize_sql(sql):
        """
        Normalize repository SQL for PostgreSQL.

        HIMP repositories historically use SQLite-compatible SQL.
        Preserve that repository contract while translating the small
        backend-specific surface at the PostgreSQL boundary.
        """
        normalized = sql.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            (
                "BIGINT GENERATED BY DEFAULT "
                "AS IDENTITY PRIMARY KEY"
            ),
        )

        return normalized.replace(
            "?",
            "%s",
        )

    def execute(
        self,
        sql,
        parameters=(),
    ):
        cursor = self.connection.cursor()

        cursor.execute(
            self._normalize_sql(sql),
            parameters,
        )

        return cursor

    def query(
        self,
        sql,
        parameters=(),
    ):
        cursor = self.connection.cursor()

        cursor.execute(
            self._normalize_sql(sql),
            parameters,
        )

        return cursor.fetchall()

    @contextmanager
    def transaction(self):
        try:
            with self.connection.transaction():
                yield self.connection

        except Exception:
            raise

    def initialize_schema(self):
        """
        Initialize the complete HIMP PostgreSQL schema atomically.

        Every schema statement is executed inside one PostgreSQL
        transaction. If any statement fails, PostgreSQL rolls back
        the entire schema initialization.
        """
        with self.connection.transaction():
            with self.connection.cursor() as cursor:
                for statement in schema_statements():
                    cursor.execute(statement)

    def close(self):
        self.connection.close()

    def table_columns(
        self,
        table_name,
    ):
        """
        Return the column names for a PostgreSQL table in the
        current schema.
        """
        rows = self.query(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = ?
            ORDER BY ordinal_position
            """,
            (
                table_name,
            ),
        )

        return {
            row["column_name"]
            for row in rows
        }

    def execute_insert(
        self,
        sql,
        parameters=(),
    ):
        """
        Execute an INSERT and return its generated integer ID.

        PostgreSQL requires the INSERT to expose the generated
        identifier through RETURNING id.
        """
        normalized_sql = sql.rstrip().rstrip(";")

        if "returning" not in normalized_sql.lower():
            normalized_sql += " RETURNING id"

        cursor = self.connection.cursor()

        cursor.execute(
            self._normalize_sql(
                normalized_sql
            ),
            parameters,
        )

        row = cursor.fetchone()

        if row is None:
            raise RuntimeError(
                "PostgreSQL INSERT did not return "
                "a generated identifier."
            )

        return row["id"]

    @staticmethod
    def is_integrity_error(exception):
        """
        Return whether an exception represents a PostgreSQL
        integrity/constraint violation.
        """
        return isinstance(
            exception,
            psycopg.IntegrityError,
        )

    def begin_lock_transaction(
        self,
        connection,
    ):
        """
        PostgreSQL transaction serialization is provided by its
        transaction/constraint semantics. No SQLite-style
        BEGIN IMMEDIATE statement is required.
        """
        return None


    def execute_transaction(
        self,
        connection,
        sql,
        parameters=(),
    ):
        """
        Execute repository SQL on an existing PostgreSQL transaction
        connection while preserving normal backend SQL translation.
        """
        return connection.execute(
            self._normalize_sql(sql),
            parameters,
        )
