# HIMP Configuration

proxmox:
  host: 10.10.37.50
  token_id: CHANGE_ME
  token_secret: CHANGE_ME
  verify_ssl: false

technitium:
  host: 10.10.37.9
  token: CHANGE_ME

unifi:
  host: 10.10.37.1
  api_key: CHANGE_ME

