---
service: "Technitium DNS"

role: "Authoritative DNS"

category: "DNS"

platform: "LXC"

vendor: "Technitium"

plugin: technitium


priority: "High"

icon: "🌍"

technitium_port: 5380
technitium_service: "Technitium DNS"
