---
###############################################################################
# Application Discovery
###############################################################################

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Discover Technitium
  ansible.builtin.include_tasks: applications/technitium.yml

- name: Assemble application discovery
  ansible.builtin.set_fact:
    discovery_applications: >-
      {{
        discovery_applications_technitium | default({})
      }}
